version: '3'



services:

  backend:
    container_name: social_backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./../backend/uploads/:/app/uploads
    env_file:
      - ./.env
    command: ["/app/entrypoint.sh"]
    depends_on:
      - postgres


  postgres:
    container_name: social_postgres
    image: 'postgres:14.2'
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ./db/postgres/:/var/lib/postgresql/data
    env_file:
      - ./.env


  mailhog:
    container_name: social_mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
