"""Post model upd

Revision ID: 2923174b4de2
Revises: e83f933d67d5
Create Date: 2023-05-12 02:56:24.795950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2923174b4de2'
down_revision = 'e83f933d67d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'profile_id')
    # ### end Alembic commands ###
