"""Following model

Revision ID: 3868686fa793
Revises: 0296f1821944
Create Date: 2023-05-12 03:41:56.444233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3868686fa793'
down_revision = '0296f1821944'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_by_id', sa.Integer(), nullable=True),
    sa.Column('profile_whom_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_by_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['profile_whom_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_by_id', 'profile_whom_id', name='unique_following')
    )
    op.create_index(op.f('ix_following_id'), 'following', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_following_id'), table_name='following')
    op.drop_table('following')
    # ### end Alembic commands ###
