"""Like id seq

Revision ID: 5aeab9d2d7c5
Revises: 3868686fa793
Create Date: 2023-05-12 09:11:42.624852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aeab9d2d7c5'
down_revision = '3868686fa793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE like_id_seq')
    op.execute('ALTER TABLE "like" ALTER COLUMN id SET DEFAULT nextval(\'like_id_seq\')')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
