"""Like model upd

Revision ID: 9bb2a2980221
Revises: 2923174b4de2
Create Date: 2023-05-12 03:09:36.603186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb2a2980221'
down_revision = '2923174b4de2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('unique_like', 'like', ['profile_id', 'post_id'])
    op.drop_constraint('like_liked_profile_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'post', ['post_id'], ['id'])
    op.drop_column('like', 'liked_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('liked_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_liked_profile_id_fkey', 'like', 'profile', ['liked_profile_id'], ['id'])
    op.drop_constraint('unique_like', 'like', type_='unique')
    op.drop_column('like', 'post_id')
    # ### end Alembic commands ###
